$content = Get-Content -Path "c:\Users\Hensu patel\Desktop\eliteoverseas-2.o\service.html" -Raw

# Replace Turnkey in Card 1
$content = $content -replace "Designing innovative spaces for modern\s*living and work", "Turnkey Projects"
$content = $content -replace "We design timeless spaces blending function,\s*beauty, and thoughtful architectural innovation\.", "Comprehensive end-to-end construction solutions.<br><br><b>Our Process</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>1. Initial Consultation</li><li>2. Concept Design</li><li>3. Detailed Planning</li><li>4. Construction Phase</li><li>5. Handover & Support</li></ul><b>Key Features</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Architectural Design & Planning</li><li>3D Modeling & Visualization</li><li>Project Management</li><li>Quality Assurance</li><li>Timely Delivery</li></ul><b>Sectors</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Residential, Commercial, Industrial, Hospitality</li></ul>"

# Replace Civil in Card 2
$content = $content -replace "Architectural renovations that\s*preserve\s*historical integrity", "Civil Engineering"
$content = $content -replace "Creating meaningful environments through\s*modern\s*design, precision, and refined architectural vision\.", "Professional civil works for strong foundations.<br><br><b>Our Process</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>1. Site Investigation</li><li>2. Structural Design</li><li>3. Foundation Work</li><li>4. Structural Construction</li><li>5. Quality Verification</li></ul><b>Key Features</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Structural Engineering</li><li>Foundation Design</li><li>Site Preparation</li><li>Concrete Works</li><li>Road & Infrastructure</li></ul><b>Sectors</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Infrastructure, Commercial, Residential, Industrial</li></ul>"

# Replace MEP in Card 3
$content = $content -replace "Comprehensive\s*planning and design for your building", "MEP Services"
$content = $content -replace "Designing sustainable,\s*modern structures that balance aesthetics, purpose, and human experience\.", "Expert mechanical, electrical & plumbing installations.<br><br><b>Our Process</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>1. System Design</li><li>2. Coordination</li><li>3. Installation</li><li>4. Testing & Commissioning</li><li>5. Maintenance</li></ul><b>Key Features</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>HVAC Systems</li><li>Electrical Installation</li><li>Plumbing Systems</li><li>Fire Safety Systems</li><li>Building Automation</li></ul><b>Sectors</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Commercial, Residential, Healthcare, Education</li></ul>"

# Replace Interior in Service v3 Item 1
$content = $content -replace "Custom residential architecture", "Interior Fit-Out"
$content = $content -replace "Architecture focused on simplicity, balance, and creating lasting impressions through design\.", "Premium interior design solutions.<br><br><b>Our Process</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>1. Space Planning</li><li>2. Design Development</li><li>3. Technical Execution</li><li>4. Finishing Touches</li><li>5. Final Handover</li></ul><b>Key Features</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Space Planning</li><li>Custom Furniture</li><li>Lighting Design</li><li>Flooring Solutions</li><li>Decorative Elements</li></ul><b>Sectors</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Office, Retail, Residential, Hospitality</li></ul>"

# Replace Steel in Service v3 Item 2
$content = $content -replace "End-to-end project management", "Steel & Structural"
$content = $content -replace "Designing sustainable, modern structures that balance aesthetics, purpose, and human experience\.", "Precision steel fabrication & engineering.<br><br><b>Our Process</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>1. Structural Design</li><li>2. Material Procurement</li><li>3. Fabrication</li><li>4. Surface Treatment</li><li>5. Erection & Installation</li></ul><b>Key Features</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Steel Fabrication</li><li>Structural Design</li><li>Welding Services</li><li>Installation & Erection</li><li>Quality Inspection</li></ul><b>Sectors</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Industrial, Commercial, Infrastructure, Warehouses</li></ul>"

# Replace Infrastructure in Service v3 Item 3
$content = $content -replace "Structural engineering solutions", "Infrastructure Development"
$content = $content -replace "Transforming spaces into inspiring environments with innovative, purposeful, and timeless architectural design\.", "Large-scale infrastructure projects.<br><br><b>Our Process</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>1. Master Planning</li><li>2. Approvals & Permits</li><li>3. Site Preparation</li><li>4. Construction</li><li>5. Testing & Handover</li></ul><b>Key Features</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Road Construction</li><li>Utility Installation</li><li>Drainage Systems</li><li>Public Facilities</li><li>Site Development</li></ul><b>Sectors</b><br><ul style='padding-left:20px; margin-top:5px; margin-bottom:5px'><li>Government, Municipal, Private, Community</li></ul>"

[IO.File]::WriteAllText("c:\Users\Hensu patel\Desktop\eliteoverseas-2.o\service.html", $content, [System.Text.Encoding]::UTF8)